# register
POST https://rental-bikes.herokuapp.com/auth/register
Content-Type: application/json

{
	"fullname": "nur muhammad ikhsan",
	"email": "nikhsan417@gmail.com",
	"password": "qwerty",
	"confirmPassword":"qwerty"
}

###

# auto verified register
POST https://rental-bikes.herokuapp.com/auth/auto-register
Content-Type: application/json

{
	"fullname": "nur muhammad ikhsan",
	"email": "nikhsan417@gmail.comssss",
	"password": "qwerty",
	"confirmPassword":"qwerty"
}

###

# login
POST https://rental-bikes.herokuapp.com/auth/login
Content-Type: application/json

{
    "email": "nikhsan417@gmail.com",
    "password": "1"
}

###

###

#get user by email
GET http://rental-bikes.herokuapp.com/users/nikhsan417@gmail.com

###

# update user profile
PUT https://rental-bikes.herokuapp.com/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5pa2hzYW40MTdAZ21haWwuY29tIiwiaWF0IjoxNjYzMzEyNTQ2LCJleHAiOjE2NjM5MTczNDZ9.NZ48imD_hVsQoFMZ8gNvJN3eOgIdXQd88gbiTVNgffU

{
	"birthPlace": "Jakarta",
	"phone": "085156796206",
	"dob": "02-08-00",
	"address": " jakarta timur"
}

###

# reset password
PUT https://rental-bikes.herokuapp.com/auth/reset-password
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5pa2hzYW40MTdAZ21haWwuY29tIiwiaWF0IjoxNjYzMzExMjA0LCJleHAiOjE2NjM5MTYwMDR9.8icFKVXk59PjS-NFa3IJFfiMcn-bg_oRD0HhxTBdPdA

{
	"currentPassword": "asdfgh",
	"newPassword": "wwqqqq",
	"confirmPassword": "qqqqweqweq"
}

###

# get all rentals
GET https://rental-bikes.herokuapp.com/rental

###

# get a rental by id
GET https://rental-bikes.herokuapp.com/rental/632d1790a8467e439d51946e

###

# get all bicycles in one rental by rental id
GET https://rental-bikes.herokuapp.com/bicycle/632d1790a8467e439d51946e

###

# create review to a rental by rental id from user

POST https://rental-bikes.herokuapp.com/review
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5pa2hzYW40MTdAZ21haWwuY29tIiwiaWF0IjoxNjYzMjk3OTgxLCJleHAiOjE2NjM5MDI3ODF9.wJzAORwfd-nv93XtESrurVwc9gfr463ZR4pRauWDKeE

{
	"rentalId": "632358108bf661fe3679a207",
	"review": "jelek bos", 
	"rating": 1
}

###

# get all reviews 

GET  https://rental-bikes.herokuapp.com/review
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5pa2hzYW40MTdAZ21haWwuY29tIiwiaWF0IjoxNjYzMjk3OTgxLCJleHAiOjE2NjM5MDI3ODF9.wJzAORwfd-nv93XtESrurVwc9gfr463ZR4pRauWDKeE